index:
    path: /
    controller: App\Controller\BookController::showAll
filter_books_by_author:
    path: /books/author/{filterId}
    controller: App\Controller\BookController::showFilteredByAuthorBooks
    requirements:
        filter: 'author|genre'
        filterId: '\d+'
    methods: ['GET']
filter_books_by_genre:
    path: /books/genre/{filterId}
    controller: App\Controller\BookController::showFilteredByGenreBooks
    requirements:
        filterId: '\d+'
    methods: ['GET']
create_book:
    path: /book/create/
    controller: App\Controller\BookController::create
    methods: ['GET', 'POST']
show_book:
    path: /book/{id}/
    controller: App\Controller\BookController::show
    requirements:
      id: '\d+'
    methods: ['GET', 'POST']
edit_book:
    path: /book/edit/{id}/
    controller: App\Controller\BookController::edit
    requirements:
      id: '\d+'
    methods: ['GET', 'POST']
remove_book:
    path: /book/remove/{id}/
    controller: App\Controller\BookController::remove
    requirements:
      id: '\d+'
    methods: ['GET']
remove_book_picure:
    path: /book/remove_picture/{id}/
    controller: App\Controller\BookController::removePicture
    requirements:
      id: '\d+'
    methods: ['GET']
genres_list:
    path: /genre/all
    controller: App\Controller\GenreController::index
create_genre:
    path: /genre/create/
    controller: App\Controller\GenreController::create
    methods: ['GET', 'POST']
edit_genre:
    path: /genre/{id}/
    controller: App\Controller\GenreController::edit
    requirements:
      id: '\d+'
    methods: ['GET', 'POST']
remove_genre:
    path: /genre/remove/{id}/
    controller: App\Controller\GenreController::remove
    requirements:
      id: '\d+'
    methods: ['GET', 'POST']
author_list:
    path: /author/all
    controller: App\Controller\AuthorController::index
create_author:
    path: /author/create/
    controller: App\Controller\AuthorController::create
    methods: ['GET', 'POST']
edit_author:
    path: /author/edit/{id}/
    controller: App\Controller\AuthorController::edit
    requirements:
      id: '\d+'
    methods: ['GET', 'POST']
remove_author:
    path: /author/remove/{id}/
    controller: App\Controller\AuthorController::remove
    requirements:
      id: '\d+'
    methods: ['GET', 'POST']
register_user:
    path: /register/
    controller: App\Controller\UserController::register
    methods: ['GET', 'POST']
login_user:
    path: /login/
    controller: App\Controller\UserController::login
    methods: ['GET', 'POST']
logout:
    path: /logout/
edit_user:
    path: /user/
    controller: App\Controller\UserController::editLogin
    methods: ['GET', 'POST']
remove_user_picure:
    path: /user/remove_picture/
    controller: App\Controller\UserController::removePicture
    methods: ['GET']
add_to_favorites:
    path: /user/favorites/add/{id}
    controller: App\Controller\UserController::addToFavorites
    requirements:
      id: '\d+'
    methods: ['GET']
remove_from_favorites:
    path: /user/favorites/remove/{id}
    controller: App\Controller\UserController::removeFromFavorites
    methods: ['GET', 'POST']