App\Entity\Author:
    type: entity
    repositoryClass: App\Repository\AuthorRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
      name:
        type: string
        length: 255
      birthday:
        type: date
      gender_id:
        type: integer