App\Entity\Genre:
    repositoryClass: App\Repository\GenreRepository
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
      genre:
        type: string
        length: 255