App\Entity\User:
    type: entity
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
      username:
        type: string
        length: 25
        unique: true
      password:
        type: string
        length: 64
      email:
        type: string
        length: 60
      is_active:
        type: boolean